version: '3'                             
services:                                
  jupyter_notebook:                      
    image:             
      jupyter/minimal-notebook
    volumes:                             
      - ./volumes:/home/ubuntu/volumes/
    restart:                            
      always
    ports:                               
      - "8888:8888"
    container_name:                     
      jupyter_notebook
    command:                             
      start-notebook.sh --NotebookApp.token=''
